name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - resume.md
      - .github/workflows/pdfrize.yml

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-japanese texlive-fonts-extra fonts-noto-cjk

      - name: Install Eisvogel template
        run: |
          # Clone Eisvogel repo (shallow) and copy the *whole* multi‑file template set
          git clone --depth 1 https://github.com/Wandmalfarbe/pandoc-latex-template.git /tmp/eisvogel
          mkdir -p ~/.pandoc/templates
          cp /tmp/eisvogel/template-multi-file/* ~/.pandoc/templates/

      - name: Convert resume.md to PDF
        run: |
          mkdir -p docs
          pandoc resume.md -o docs/resume.pdf \
            --pdf-engine=xelatex \
            -V mainfont="Noto Sans CJK JP" \
            -V sansfont="Noto Sans CJK JP" \
            -V monofont="Noto Sans Mono CJK JP" \
            -V fontsize=11pt \
            -V geometry=top=25mm,bottom=25mm,left=25mm,right=25mm

      - name: Commit PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/resume.pdf
          git commit -m "🤖 Auto-generate PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
