name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - 'resume.md'

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-japanese

      - name: Convert resume.md to PDF
        run: |
          mkdir -p docs
          pandoc resume.md -o docs/resume.pdf --pdf-engine=lualatex -V documentclass=ltjarticle

      - name: Commit PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/resume.pdf
          git commit -m "Auto-generate PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}