name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - resume.md
      - .github/workflows/pdfrize.yml

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pandoc and LaTeX and Font
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-japanese
          sudo apt-get install -y fonts-noto-cjk

      - name: Install Eisvogel template
        run: |
          mkdir -p ~/.pandoc/templates
          curl -L https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/template-multi-file/eisvogel.latex -o ~/.pandoc/templates/eisvogel.latex

      - name: Convert resume.md to PDF
        run: |
          mkdir -p docs
          pandoc resume.md -o docs/resume.pdf \
            --pdf-engine=xelatex \
            --template=eisvogel \
            -V mainfont="Noto Sans CJK JP" \
            -V titlepage=false \
            -V toc=false \
            -V colorlinks=true

      - name: Commit PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/resume.pdf
          git commit -m "🤖 Auto-generate PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
