name: Convert Markdown to PDF

on:
  push:
    branches:
      - main
    paths:
      - resume.md
      - .github/workflows/pdfrize.yml

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-lang-japanese texlive-fonts-extra fonts-noto-cjk

      # - name: Install Simple template
      #   run: |
      #     mkdir -p ~/.pandoc/templates
      #     curl -L https://raw.githubusercontent.com/Wandmalfarbe/pandoc-latex-template/master/examples/simple.latex -o ~/.pandoc/templates/simple.latex

      # - name: Convert resume.md to PDF
      #   run: |
      #     mkdir -p docs
      #     pandoc resume.md -o docs/resume.pdf \
      #       --pdf-engine=xelatex \
      #       --template=simple \
      #       -V mainfont="Noto Sans CJK JP" \
      #       -V sansfont="Noto Sans CJK JP" \
      #       -V monofont="Noto Sans Mono CJK JP" \
      #       -V colorlinks=true \
      #       -V linkcolor=blue
      #          -V fontsize=11pt \
      #             -V geometry=top=25mm,bottom=25mm,left=25mm,right=25mm

      - name: Convert Markdown to HTML
        run: |
          pandoc resume.md -o docs/resume.html \
            --standalone \
            --css=assets/vscode-light.css

      - name: Install Puppeteer
        run: npm install -g puppeteer-cli

      - name: Convert HTML to PDF
        run: |
          npx puppeteer-cli print docs/resume.html docs/resume.pdf

      - name: Commit PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/resume.pdf
          git commit -m "🤖 Auto-generate PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
